compressionLevel: 0

enableGlobalCache: true

enableTelemetry: false

nodeLinker: node-modules

npmAuthToken: "${PANDELL_NPM_TOKEN}"

yarnPath: .yarn/releases/yarn-4.3.1.cjs

# Fix transitive peer dependencies warning in yarn 4.3.0+
# For more info see "PR#6205: Rework peer requirement and warning system",
# https://github.com/yarnpkg/berry/pull/6205
# https://yarnpkg.com/configuration/yarnrc#packageExtensions
packageExtensions:
  {
    "@eslint-react/ast@*": { peerDependencies: { "eslint": ">= 9", "typescript": ">= 5" } },
    "@eslint-react/core@*": { peerDependencies: { "eslint": ">= 9", "typescript": ">= 5" } },
    "@eslint-react/jsx@*": { peerDependencies: { "eslint": ">= 9", "typescript": ">= 5" } },
    "@eslint-react/shared@*": { peerDependencies: { "eslint": ">= 9", "typescript": ">= 5" } },
    "@eslint-react/types@*": { peerDependencies: { "eslint": ">= 9", "typescript": ">= 5" } },
    "@eslint-react/var@*": { peerDependencies: { "eslint": ">= 9", "typescript": ">= 5" } },
    "@tanstack/eslint-plugin-query@*": { peerDependencies: { "typescript": ">= 5" } },
    "@typescript-eslint/type-utils@*": { peerDependencies: { "eslint": ">= 9" } },
    "@typescript-eslint/utils@*": { peerDependencies: { "typescript": ">= 5" } },
    "eslint-plugin-import-x@*": { peerDependencies: { "typescript": ">= 5" } },
    "eslint-plugin-vitest@*": { peerDependencies: { "typescript": ">= 5" } },
    "typescript-eslint@*": { peerDependencies: { "eslint": ">= 9" } },
  }
