name: Publish a package on a new release
on:
  release:
    types: [created]
jobs:
  publish_github:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '16.x'
        registry-url: 'https://npm.pkg.github.com'
        scope: '@pandell'
    - run: yarn
    - run: yarn build
    - run: yarn publish
      env:
        NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  publish_myget:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '16.x'
        registry-url: 'https://www.myget.org/F/pandell-npm/npm/'
        scope: '@pandell'
    - run: yarn
    - run: yarn build
    # workaround to reset registry in temp npmrc file
    - run: echo "registry=https://www.myget.org/F/pandell-npm/npm/" >> .npmrc
    - run: yarn publish
      env:
        NODE_AUTH_TOKEN: ${{ secrets.MYGET_TOKEN }}
