name: Publish a package on a new release
on:
  release:
    types: [created]
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
    # publish to GitHub package repository
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '16.x'
        registry-url: 'https://npm.pkg.github.com'
        scope: '@pandell'
    - run: yarn
    - run: yarn build
    - run: yarn publish
      env:
        NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    # publish to Pandell's MyGet package repository
    - uses: actions/setup-node@v2
      with:
        registry-url: 'https://www.myget.org/F/pandell-npm/npm/'
        scope: '@pandell'
    - run: yarn publish
      env:
        NODE_AUTH_TOKEN: ${{ secrets.MYGET_TOKEN }}
